version: '3.8'

services:
  whisperfusion:
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        CUDA_ARCH: ${CUDA_ARCH:-89-real;90-real}
    image: nepali_whisperfusion:latest
    volumes:
      - type: bind
        source: ./docker/scratch-space
        target: /root/scratch-space
    environment:
      VERBOSE: ${VERBOSE:-false}
    ports:
      - "8017:8888"
      - "8016:6006"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    entrypoint: ["/root/scratch-space/run-whisperfusion.sh"]

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/resources/docker/default:/etc/nginx/conf.d/default.conf:ro
      - ./examples/chatbot/html:/var/www/html:ro
      - ./docker/scripts/start-nginx.sh:/start-nginx.sh:ro

    ports:
      - "8018:80"
    depends_on:
      - whisperfusion
    entrypoint: ["/bin/bash", "/start-nginx.sh"]
